services:
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: electromart-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
      - MYSQL_DATABASE=electromart
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
